### ISSUE TITLE
about pretrain model

### ISSUE THREAD

**Issue by ygjwd12345** [fcdl94/MiB#16]
Hi，
I want to reproduce your work.
but I get an error as follow
FileNotFoundError: [Errno 2] No such file or directory: 'pretrained/resnet101_iabn_sync.pth.tar'
can you tell me how to get it?

**Comment by ygjwd12345** [comment]
I find it  
thanks

**Comment by deepaksinghcv** [comment]
@ygjwd12345 Could you tell me how you resolved this issue?
I'm facing similar issue

**Comment by fcdl94** [comment]
Hi @deepakksingh. 
I've seen only now your comment.
That's the link: https://github.com/mapillary/inplace_abn#training-on-imagenet-1k (click on md5 to get the download page).
If you open the link, there's a table. The last row is the pretrained model you need, but in case you want to try different architecture, you can just download the pretrained and specify the correct backbone.

**Comment by deepaksinghcv** [comment]
@fcdl94 Thank you for your reply.
I did the same. I downloaded it from the Google drive and renamed it accordingly.

**Comment by EricKani** [comment]
> @fcdl94 Thank you for your reply.
> I did the same. I downloaded it from the Google drive and renamed it accordingly.

Hi~ I download corresponding pth.tar file for this project from inpace_abn repository. But the parameters' name doesn't match. Do you encounter this problem?

thanks~

**Comment by fcdl94** [comment]
Hi!

Which parameters does not match? That's strange since I took their resent and deeplab implementation (have you specified the norm_act parameter maybe?)

**Comment by deepaksinghcv** [comment]
I faced the issue where "module" word was not matching. That happens when the model was trained and saved as per multi-gpu setting. So you may have to rename some parameter names to remove the "module" word

**Comment by deepaksinghcv** [comment]
Follow up : The renaming issue is mentioned here : https://github.com/fcdl94/MiB/issues/14#issuecomment-633503627

**Comment by EricKani** [comment]
> I faced the issue where "module" word was not matching. That happens when the model was trained and saved as per multi-gpu setting. So you may have to rename some parameter names to remove the "module" word

yes, it is the reason why not matched. ~ I didn't read README carefully. Thank you~

**Comment by EricKani** [comment]
> Hi!
> 
> Which parameters does not match? That's strange since I took their resent and deeplab implementation (have you specified the norm_act parameter maybe?)

Thanks for your reply. It is the reason of "module." in pretrained model's state_dict's keys~
