### ISSUE TITLE
How do i infer the logs or tensorboard?

### ISSUE THREAD

**Issue by deepaksinghcv** [fcdl94/MiB#21]
Hello @fcdl94, I really liked your research work, and I was trying to reproduce the results.
I tried for 19-1, 15-5, and 15-5s split on PASCAL VOC. The command shown below is for the 19-1 split.
Could you also please confirm whether these default settings are enough to reproduce the result in **Table 1: Mean IoU on the Pascal-VOC 2012 dataset for different incremental class learning scenarios** of your research paper?
```
#disjoint
python -m torch.distributed.launch --nproc_per_node=4 run.py --data_root /ssd_scratch/cvit/dksingh/ --batch_size 6 --dataset voc --name MiB --task 19-1 --step 0 --lr 0.01 --epochs 30 --method MiB --logdir /ssd_scratch/cvit/dksingh/mib_logs/
python -m torch.distributed.launch --nproc_per_node=4 run.py --data_root /ssd_scratch/cvit/dksingh/ --batch_size 6 --dataset voc --name MiB --task 19-1 --step 1 --lr 0.001 --epochs 30 --method MiB --logdir /ssd_scratch/cvit/dksingh/mib_logs/

#overlap
python -m torch.distributed.launch --nproc_per_node=4 run.py --data_root /ssd_scratch/cvit/dksingh/ --batch_size 6 --dataset voc --name MiB --task 19-1 --step 0 --lr 0.01 --epochs 30 --method MiB --logdir /ssd_scratch/cvit/dksingh/mib_logs/ --overlap
python -m torch.distributed.launch --nproc_per_node=4 run.py --data_root /ssd_scratch/cvit/dksingh/ --batch_size 6 --dataset voc --name MiB --task 19-1 --step 1 --lr 0.001 --epochs 30 --method MiB --logdir /ssd_scratch/cvit/dksingh/mib_logs/ --overlap
```
I was wondering on infering the tensorboard logs or the general log file

**Comment by fcdl94** [comment]
Hi @deepakksingh! 
The command should be right and should be enough to reproduce it.

Do you mean how to infer the results from the tensorboard log?
The code adds a table on the tensorboard which contains the results after the last epochs. 
You can find in TEXT/Results a table with four rows: Val-Acc, Val-IoU, Test-IoU, Test-Acc. 
The reported results are the one in the line Test-IoU but removing the background from the average (since the background class is not a class of interest for the performance).

I hope of having understood the question, otherwise, please, can you clarify?

**Comment by deepaksinghcv** [comment]
Thank you for your prompt reply.
I'm a bit confused while understanding the tensorboard logs.
I have attached the following screenshots for Disjoint 19-1 training
The _all_ IoU of 67.4 is being found in the logs(stdout), and their classwise IoUs are also in the tensorboard logs.
**May I know where do the IoUs 69.6 and 25.6 found in the tensorboard, or how do I calculate them?**

Screenshot of the paper showing disjoint 19-1:
![Screenshot from 2020-09-03 14-45-50](https://user-images.githubusercontent.com/26389049/92096177-3548fb80-edf4-11ea-8236-f67bb9fb5752.png)

Result after step-1 of disjoint 19-1:
![Screenshot from 2020-09-03 14-34-14](https://user-images.githubusercontent.com/26389049/92095528-6c6add00-edf3-11ea-9c04-87db180209b7.png)

Tensorboard result after step-0 of disjoint 19-1:
![Screenshot from 2020-09-03 15-24-16](https://user-images.githubusercontent.com/26389049/92100563-958e6c00-edf9-11ea-82fa-2f187240ec31.png)

Tensorboard result after step-1 of disjoint 19-1:
![Screenshot from 2020-09-03 15-23-01](https://user-images.githubusercontent.com/26389049/92100418-6a0b8180-edf9-11ea-874c-9d38fc507155.png)

Screenshot of the logs showing result after step-0 of disjoint 19-1
![Screenshot from 2020-09-03 14-49-26](https://user-images.githubusercontent.com/26389049/92096973-30387c00-edf5-11ea-80f6-69af62407df7.png)

**Comment by fcdl94** [comment]
Yes, it may not be intuitive.
Actually, what I made to computed the partial mIoU (19-1 and 20) was making a Google sheet with all the per-class results and then averaging directly there.
It's perfectly fine, since mIoU is computed as a mean by classes.
However, you can see the mIoU for class 20 directly in the last column of the tensor board results after step 1. I must admin that you got 18.3 instead of 25.4 for it, so there may be some issue in the script you used to run it or it may be due to the variability of the 19-1 setting. Can you ran the 15-5 to check it is ok?

**Comment by deepaksinghcv** [comment]
I'm attaching the screenshots for the 15-5 disjoint experiment on voc:

Screenshot with the highlighted region:
![Screenshot from 2020-09-03 22-36-16](https://user-images.githubusercontent.com/26389049/92145468-e754e780-ee35-11ea-8077-9e799c0516d6.png)

Tensorboard table after step-1 of disjoint 15-5 on voc for MiB:
![mib_voc_15_5_disjoint_step1_tensorboard](https://user-images.githubusercontent.com/26389049/92145491-ec199b80-ee35-11ea-8821-f15f06dde665.png)

List of class IoUs after step-1 of disjoint 15-5 on voc for MiB:
![mib_voc_15_5_disjoint_step1_sublime](https://user-images.githubusercontent.com/26389049/92145501-ef148c00-ee35-11ea-8849-bbd4ddd3ab60.png)

**I got confused on finding 21 classes: class-0 to class 20**
I believe with my experiment setting I'm having the following, Could you kindly confirm them.
**For _all_ : Reproduced: 65.2, Paper's: 64.7**
I got confused while calculating _1-15_ and _16-20_, so as mentioned in the above image where the list of class IoUs are shown, I calculated the mIoU whose results are shown below:

mIoU of class 1-15 | 71.09 | mIoU of class 16-20 | 42.6
-- | -- | -- | --
mIoU of class 0-14 | 71.39 | mIoU of class 15-19 | 48.88

**The paper's results are 71.8 for class 1-15 and 43.3 for class 16-20.**
So I believe the IoU calculation of the 1st row is correct, which can also mean that class 0  is unnecessary. Kindly confirm this too.

Thank you and sorry for bothering you this much.

**Comment by fcdl94** [comment]
Hi @deepakksingh!
Yes, you're correct. Class 0 (which is the background) has been excluded from the results.
The first way of calculating results is correct 1-15 for old and 16-20 new for the 15-1 and 15-5 settings, 1-19 for old and 20 for new in the 19-1.
Also from the _all_ I excluded the background, so be sure that also the all is between 1-20, and not 0-20.

It's my pleasure to see people interested in this work, no bother at all :) 
Let me know if now it's clear how to compute results 👍

**Comment by deepaksinghcv** [comment]
Thank you so much for clarifying my doubts.
I'm currently reproducing results on ADE.
But I will close this issue for the time being.

PS: I really appreciate your codebase, it's very elegant.
