### ISSUE TITLE
About reproducing "Disjoint 15-5s" setting

### ISSUE THREAD

**Issue by zhangchbin** [fcdl94/MiB#24]
Hi, when I was reproducing the 15-5s mission, there was a problem.
I got the performance of the last model (21 classes) as following:

`Class IoU:
        class 0: 0.8489214
        class 1: 0.16607599
        class 2: 0.287244
        class 3: 0.33080766
        class 4: 0.08697148
        class 5: 0.37604603
        class 6: 0.0072344807
        class 7: 0.2163677
        class 8: 0.6778649
        class 9: 0.010483054
        class 10: 0.28229013
        class 11: 0.08285885
        class 12: 0.54856247
        class 13: 0.5060702
        class 14: 0.26826012
        class 15: 0.79161125
        class 16: 0.00043867234
        class 17: 0.22526477
        class 18: 0.13574767
        class 19: 0.14906816
        class 20: 0.2198876
Class Acc:
        class 0: 0.9055752
        class 1: 0.1661803
        class 2: 0.45422554
        class 3: 0.33121628
        class 4: 0.08705099
        class 5: 0.38315275
        class 6: 0.0072452705
        class 7: 0.21683867
        class 8: 0.6815347
        class 9: 0.010607969
        class 10: 0.301625
        class 11: 0.083156176
        class 12: 0.59717894
        class 13: 0.5174191
        class 14: 0.27290416
        class 15: 0.86344343
        class 16: 0.0004472701
        class 17: 0.70130014
        class 18: 0.41352695
        class 19: 0.9158315
        class 20: 0.64600176
`

I used the command as following:
`CUDA_VISIBLE_DEVICES=1 python -m torch.distributed.launch --nproc_per_node=1 run.py \
    --batch_size 10 \
    --dataset voc \
	--name MIB_lr0-01_for_step0_lr0-001_for_step1 \
    --task 15-5s \
    --step 0 \
    --lr 0.01 \
    --epochs 30 \
    --method MiB \
    --opt_level O1 \

CUDA_VISIBLE_DEVICES=1 python -m torch.distributed.launch --nproc_per_node=1 run.py \
    --batch_size 10 \
    --dataset voc \
	--name MIB_lr0-01_for_step0_lr0-001_for_step1 \
    --task 15-5s \
    --step 1 \
    --lr 0.001 \
    --epochs 30 \
    --method MiB \
    --opt_level O1 \

CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=2 run.py \
    --batch_size 10 \
    --dataset voc \
	--name MIB_lr0-01_for_step0_lr0-001_for_step1 \
    --task 15-5s \
    --step 2 \
    --lr 0.001 \
    --epochs 30 \
    --method MiB \
    --opt_level O1 \

CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=2 run.py \
    --batch_size 10 \
    --dataset voc \
	--name MIB_lr0-01_for_step0_lr0-001_for_step1 \
    --task 15-5s \
    --step 3 \
    --lr 0.001 \
    --epochs 30 \
    --method MiB \
    --opt_level O1 \

CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=2 run.py \
    --batch_size 10 \
    --dataset voc \
	--name MIB_lr0-01_for_step0_lr0-001_for_step1 \
    --task 15-5s \
    --step 4 \
    --lr 0.001 \
    --epochs 30 \
    --method MiB \
    --opt_level O1 \

CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=2 run.py \
    --batch_size 10 \
    --dataset voc \
	--name MIB_lr0-01_for_step0_lr0-001_for_step1 \
    --task 15-5s \
    --step 5 \
    --lr 0.001 \
    --epochs 30 \
    --method MiB \
    --opt_level O1 \`

**Comment by fcdl94** [comment]
Hi @zhangchbin,
It is due to the fact that this setting requires a different weight for the distillation loss.
Please refer to https://github.com/fcdl94/MiB/issues/22#issuecomment-699469815 for the instructions to replicate the results.

**Comment by zhangchbin** [comment]
Hi, @fcdl94 ,
I used the setting as referred in it, and I got the mIoU: (1-20) 30.20, (1-15) 13.54.
Is it correct?

**Comment by fcdl94** [comment]
No, there results are still wrong.
Can you send the whole script that you run?
You should get results close to the paper, and reproduced here https://github.com/fcdl94/MiB/issues/22#issuecomment-700338838.

One thing I surely see as wrong is the batch size, that should be 12 per gpu (however, using 10 per gpu should approximate the results)

**Comment by zhangchbin** [comment]
For the model in Step-0, should I use the same setting to train? Currently, I use the trained model in the setting of 15-5 task (not 15-5s) in step-0.

**Comment by fcdl94** [comment]
Yes, you can use the pretrained on 15-5 (actually, it's what I did).

**Comment by zhangchbin** [comment]
I use batchsize=10, which is limited by GPU memory.
I think this may not bring such huge impact.
It seemed that the results are not stable, I will try to run more times.

**Comment by zhangchbin** [comment]
`CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=2 run.py \
    --batch_size 10 \
    --dataset voc \
	--name MIB_lr0-01_for_step0_lr0-001_for_step1 \
    --task 15-5s \
    --step 5 \
    --lr 0.001 \
    --epochs 30 \
    --unce \
    --unkd \
    --loss_kd 100 \
    --init_balanced \
    --opt_level O1 \`

Is it correct?

**Comment by fcdl94** [comment]
Yes, it should be correct. 

Just to be sure, in this comment, have you correctly reported the numbers? Because the 16-20 should be close to 12/13, while on all classes (1-20) I expect something like 35/37.

> Hi, @fcdl94 ,
> I used the setting as referred in it, and I got the mIoU: (1-20) 30.20, (1-15) 13.54.
> Is it correct?

**Comment by zhangchbin** [comment]
Hi, @fcdl94 ,
  I run the code again.
`	class 1: 0.37673628
	class 2: 0.37846893
	class 3: 0.26021096
	class 4: 0.17804113
	class 5: 0.341187
	class 6: 0.11472182
	class 7: 0.6655937
	class 8: 0.7363883
	class 9: 3.565509e-05
	class 10: 0.085300885
	class 11: 0.05767889
	class 12: 0.592793
	class 13: 0.49509466
	class 14: 0.37592646
	class 15: 0.7549483
	class 16: 0.09576442
	class 17: 0.19244675
	class 18: 0.112534985
	class 19: 0.18334906
	class 20: 0.10120822
`

**Comment by fcdl94** [comment]
It seems that you are still having different results.
These are the results I got, class by class:
<img width="1216" alt="15-5disj" src="https://user-images.githubusercontent.com/10979083/96569057-f3ebad00-12c8-11eb-83aa-3045786e6355.png">

Checking your first comment, I see that there may be an error in the initial steps. In particular, you were running steps 0 and 1 on a single GPU with batch size 10. Can you check it?

**Comment by wuyujack** [comment]
> Hi, when I was reproducing the 15-5s mission, there was a problem.
> I got the performance of the last model (21 classes) as following:
> 
> `Class IoU: class 0: 0.8489214 class 1: 0.16607599 class 2: 0.287244 class 3: 0.33080766 class 4: 0.08697148 class 5: 0.37604603 class 6: 0.0072344807 class 7: 0.2163677 class 8: 0.6778649 class 9: 0.010483054 class 10: 0.28229013 class 11: 0.08285885 class 12: 0.54856247 class 13: 0.5060702 class 14: 0.26826012 class 15: 0.79161125 class 16: 0.00043867234 class 17: 0.22526477 class 18: 0.13574767 class 19: 0.14906816 class 20: 0.2198876 Class Acc: class 0: 0.9055752 class 1: 0.1661803 class 2: 0.45422554 class 3: 0.33121628 class 4: 0.08705099 class 5: 0.38315275 class 6: 0.0072452705 class 7: 0.21683867 class 8: 0.6815347 class 9: 0.010607969 class 10: 0.301625 class 11: 0.083156176 class 12: 0.59717894 class 13: 0.5174191 class 14: 0.27290416 class 15: 0.86344343 class 16: 0.0004472701 class 17: 0.70130014 class 18: 0.41352695 class 19: 0.9158315 class 20: 0.64600176 `
> 
> I used the command as following:
> `CUDA_VISIBLE_DEVICES=1 python -m torch.distributed.launch --nproc_per_node=1 run.py
> --batch_size 10
> --dataset voc
> --name MIB_lr0-01_for_step0_lr0-001_for_step1
> --task 15-5s
> --step 0
> --lr 0.01
> --epochs 30
> --method MiB
> --opt_level O1 \
> 
> CUDA_VISIBLE_DEVICES=1 python -m torch.distributed.launch --nproc_per_node=1 run.py
> --batch_size 10
> --dataset voc
> --name MIB_lr0-01_for_step0_lr0-001_for_step1
> --task 15-5s
> --step 1
> --lr 0.001
> --epochs 30
> --method MiB
> --opt_level O1 \
> 
> CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=2 run.py
> --batch_size 10
> --dataset voc
> --name MIB_lr0-01_for_step0_lr0-001_for_step1
> --task 15-5s
> --step 2
> --lr 0.001
> --epochs 30
> --method MiB
> --opt_level O1 \
> 
> CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=2 run.py
> --batch_size 10
> --dataset voc
> --name MIB_lr0-01_for_step0_lr0-001_for_step1
> --task 15-5s
> --step 3
> --lr 0.001
> --epochs 30
> --method MiB
> --opt_level O1 \
> 
> CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=2 run.py
> --batch_size 10
> --dataset voc
> --name MIB_lr0-01_for_step0_lr0-001_for_step1
> --task 15-5s
> --step 4
> --lr 0.001
> --epochs 30
> --method MiB
> --opt_level O1 \
> 
> CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=2 run.py
> --batch_size 10
> --dataset voc
> --name MIB_lr0-01_for_step0_lr0-001_for_step1
> --task 15-5s
> --step 5
> --lr 0.001
> --epochs 30
> --method MiB
> --opt_level O1 `

Hi @fcdl94 and @zhangchbin, just mention that I also noticed @zhangchbin was using the `--opt level O1` for training. As the `O1` are for mixed-precision training, should it also be the reason for the degradation of the mIoU?

**Comment by zhangchbin** [comment]
> It seems that you are still having different results.
> These are the results I got, class by class:
> <img alt="15-5disj" width="1216" src="https://user-images.githubusercontent.com/10979083/96569057-f3ebad00-12c8-11eb-83aa-3045786e6355.png">
> 
> Checking your first comment, I see that there may be an error in the initial steps. In particular, you were running steps 0 and 1 on a single GPU with batch size 10. Can you check it?

Hi, @fcdl94 , I do not use this command to train the model. I train the model use batch_size=10 (total 20, 2 GPUS).

**Comment by zhangchbin** [comment]
> > Hi, when I was reproducing the 15-5s mission, there was a problem.
> > I got the performance of the last model (21 classes) as following:
> > `Class IoU: class 0: 0.8489214 class 1: 0.16607599 class 2: 0.287244 class 3: 0.33080766 class 4: 0.08697148 class 5: 0.37604603 class 6: 0.0072344807 class 7: 0.2163677 class 8: 0.6778649 class 9: 0.010483054 class 10: 0.28229013 class 11: 0.08285885 class 12: 0.54856247 class 13: 0.5060702 class 14: 0.26826012 class 15: 0.79161125 class 16: 0.00043867234 class 17: 0.22526477 class 18: 0.13574767 class 19: 0.14906816 class 20: 0.2198876 Class Acc: class 0: 0.9055752 class 1: 0.1661803 class 2: 0.45422554 class 3: 0.33121628 class 4: 0.08705099 class 5: 0.38315275 class 6: 0.0072452705 class 7: 0.21683867 class 8: 0.6815347 class 9: 0.010607969 class 10: 0.301625 class 11: 0.083156176 class 12: 0.59717894 class 13: 0.5174191 class 14: 0.27290416 class 15: 0.86344343 class 16: 0.0004472701 class 17: 0.70130014 class 18: 0.41352695 class 19: 0.9158315 class 20: 0.64600176 `
> > I used the command as following:
> > `CUDA_VISIBLE_DEVICES=1 python -m torch.distributed.launch --nproc_per_node=1 run.py
> > --batch_size 10
> > --dataset voc
> > --name MIB_lr0-01_for_step0_lr0-001_for_step1
> > --task 15-5s
> > --step 0
> > --lr 0.01
> > --epochs 30
> > --method MiB
> > --opt_level O1 \
> > CUDA_VISIBLE_DEVICES=1 python -m torch.distributed.launch --nproc_per_node=1 run.py
> > --batch_size 10
> > --dataset voc
> > --name MIB_lr0-01_for_step0_lr0-001_for_step1
> > --task 15-5s
> > --step 1
> > --lr 0.001
> > --epochs 30
> > --method MiB
> > --opt_level O1 \
> > CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=2 run.py
> > --batch_size 10
> > --dataset voc
> > --name MIB_lr0-01_for_step0_lr0-001_for_step1
> > --task 15-5s
> > --step 2
> > --lr 0.001
> > --epochs 30
> > --method MiB
> > --opt_level O1 \
> > CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=2 run.py
> > --batch_size 10
> > --dataset voc
> > --name MIB_lr0-01_for_step0_lr0-001_for_step1
> > --task 15-5s
> > --step 3
> > --lr 0.001
> > --epochs 30
> > --method MiB
> > --opt_level O1 \
> > CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=2 run.py
> > --batch_size 10
> > --dataset voc
> > --name MIB_lr0-01_for_step0_lr0-001_for_step1
> > --task 15-5s
> > --step 4
> > --lr 0.001
> > --epochs 30
> > --method MiB
> > --opt_level O1 \
> > CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=2 run.py
> > --batch_size 10
> > --dataset voc
> > --name MIB_lr0-01_for_step0_lr0-001_for_step1
> > --task 15-5s
> > --step 5
> > --lr 0.001
> > --epochs 30
> > --method MiB
> > --opt_level O1 `
> 
> Hi @fcdl94 and @zhangchbin, just mention that I also noticed @zhangchbin was using the `--opt level O1` for training. As the `O1` are for mixed-precision training, should it also be the reason for the degradation of the mIoU?

Hi, @wuyujack , I have reproduced the performance of disjoint 15-5 using FP16, which do not reduce the performance. I think
there are some other reasons, such as unstable training caused by few training samples. Do you have any ideas? Thanks.

**Comment by zhangchbin** [comment]
The performance of all tasks:

STEP-1:
`INFO:rank0: 
Total samples: 1278.000000
Overall Acc: 0.930784
Mean Acc: 0.851256
FreqW Acc: 0.886603
Mean IoU: 0.747880
Class IoU:
        class 0: 0.9179936
        class 1: 0.863202
        class 2: 0.4161588
        class 3: 0.8866827
        class 4: 0.6622782
        class 5: 0.8052109
        class 6: 0.91628236
        class 7: 0.88390934
        class 8: 0.9243192
        class 9: 0.45192203
        class 10: 0.8265361
        class 11: 0.56116116
        class 12: 0.8766891
        class 13: 0.8289734
        class 14: 0.8642089
        class 15: 0.8528226
        class 16: 0.17560674
Class Acc:
        class 0: 0.9513421
        class 1: 0.9104907
        class 2: 0.8786463
        class 3: 0.9126469
        class 4: 0.7294166
        class 5: 0.88442236
        class 6: 0.9258237
        class 7: 0.92153823
        class 8: 0.9605761
        class 9: 0.56043965
        class 10: 0.8542516
        class 11: 0.61905605
        class 12: 0.9508594
        class 13: 0.90941644
        class 14: 0.9292686
        class 15: 0.913161
        class 16: 0.6599924
`

STEP-2
`INFO:rank0: 
Total samples: 1330.000000
Overall Acc: 0.904957
Mean Acc: 0.676636
FreqW Acc: 0.841535
Mean IoU: 0.593188
Class IoU:
        class 0: 0.9085323
        class 1: 0.72360253
        class 2: 0.42209065
        class 3: 0.7805046
        class 4: 0.38624403
        class 5: 0.658399
        class 6: 0.75022596
        class 7: 0.8023403
        class 8: 0.8528798
        class 9: 0.12325778
        class 10: 0.5556461
        class 11: 0.28723836
        class 12: 0.78458387
        class 13: 0.7642493
        class 14: 0.7764061
        class 15: 0.8344527
        class 16: 0.13336152
        class 17: 0.13336372
Class Acc:
        class 0: 0.96702564
        class 1: 0.730829
        class 2: 0.76962954
        class 3: 0.79046756
        class 4: 0.40202084
        class 5: 0.69590116
        class 6: 0.7532837
        class 7: 0.86156505
        class 8: 0.92054904
        class 9: 0.12818731
        class 10: 0.7724584
        class 11: 0.2914633
        class 12: 0.8834566
        class 13: 0.8614537
        class 14: 0.80879897
        class 15: 0.92089874
        class 16: 0.3508305
        class 17: 0.27062896
`

STEP-3:
`Total samples: 1354.000000
Overall Acc: 0.827741
Mean Acc: 0.653081
FreqW Acc: 0.767107
Mean IoU: 0.528566
Class IoU:
        class 0: 0.83321536
        class 1: 0.70042324
        class 2: 0.4136958
        class 3: 0.60445017
        class 4: 0.39873737
        class 5: 0.50332445
        class 6: 0.67894965
        class 7: 0.8003089
        class 8: 0.8274363
        class 9: 0.084529065
        class 10: 0.45644888
        class 11: 0.3202911
        class 12: 0.7277872
        class 13: 0.6901624
        class 14: 0.6855621
        class 15: 0.8168234
        class 16: 0.13357075
        class 17: 0.22858891
        class 18: 0.13845159
Class Acc:
        class 0: 0.86826557
        class 1: 0.7042188
        class 2: 0.76171625
        class 3: 0.60867786
        class 4: 0.41905093
        class 5: 0.5265917
        class 6: 0.68105793
        class 7: 0.8231535
        class 8: 0.91386914
        class 9: 0.09016565
        class 10: 0.5060059
        class 11: 0.32684356
        class 12: 0.8971719
        class 13: 0.74976593
        class 14: 0.70438373
        class 15: 0.93105066
        class 16: 0.48081678
        class 17: 0.5526554
        class 18: 0.8630821
`

STEP-4:
`Total samples: 1422.000000
Overall Acc: 0.793724
Mean Acc: 0.543384
FreqW Acc: 0.731323
Mean IoU: 0.404048
Class IoU:
        class 0: 0.84172684
        class 1: 0.5599737
        class 2: 0.3917242
        class 3: 0.26858926
        class 4: 0.2921927
        class 5: 0.31363845
        class 6: 0.50043887
        class 7: 0.7535024
        class 8: 0.71579874
        class 9: 0.00074676704
        class 10: 0.17163414
        class 11: 0.07188845
        class 12: 0.5870896
        class 13: 0.532097
        class 14: 0.61732376
        class 15: 0.7737817
        class 16: 0.09369166
        class 17: 0.19656046
        class 18: 0.1332674
        class 19: 0.26529866
Class Acc:
        class 0: 0.8697958
        class 1: 0.5620463
        class 2: 0.7282819
        class 3: 0.26882043
        class 4: 0.29608354
        class 5: 0.31963044
        class 6: 0.528884
        class 7: 0.76774997
        class 8: 0.7415217
        class 9: 0.00074832136
        class 10: 0.1742995
        class 11: 0.07214494
        class 12: 0.66254944
        class 13: 0.55365497
        class 14: 0.6358138
        class 15: 0.92459464
        class 16: 0.411702
        class 17: 0.7846009
        class 18: 0.72826904
        class 19: 0.83649933
`

STEP-5:
`Total samples: 1450.000000
Overall Acc: 0.742291
Mean Acc: 0.474390
FreqW Acc: 0.680791
Mean IoU: 0.333736
Class IoU:
        class 0: 0.7988254
        class 1: 0.41873047
        class 2: 0.37218413
        class 3: 0.24261844
        class 4: 0.19812956
        class 5: 0.31125414
        class 6: 0.14344287
        class 7: 0.66464204
        class 8: 0.73953164
        class 9: 3.337789e-05
        class 10: 0.10884679
        class 11: 0.06508978
        class 12: 0.5854252
        class 13: 0.4940473
        class 14: 0.4117516
        class 15: 0.7640799
        class 16: 0.09521694
        class 17: 0.1853493
        class 18: 0.11028443
        class 19: 0.18859789
        class 20: 0.11036698
Class Acc:
        class 0: 0.8203498
        class 1: 0.41893992
        class 2: 0.6587685
        class 3: 0.24279933
        class 4: 0.20002669
        class 5: 0.31511793
        class 6: 0.1450362
        class 7: 0.6697698
        class 8: 0.7778339
        class 9: 3.3430162e-05
        class 10: 0.10952233
        class 11: 0.06516313
        class 12: 0.66676384
        class 13: 0.50268257
        class 14: 0.41466647
        class 15: 0.93169403
        class 16: 0.41048625
        class 17: 0.76448894
        class 18: 0.7595911
        class 19: 0.92924476
        class 20: 0.15921436
`

**Comment by fcdl94** [comment]
Can you also send the commands and the aggregated results? Otherwise is hard to help.

**Comment by wuyujack** [comment]
> > > Hi, when I was reproducing the 15-5s mission, there was a problem.
> > > I got the performance of the last model (21 classes) as following:
> > > `Class IoU: class 0: 0.8489214 class 1: 0.16607599 class 2: 0.287244 class 3: 0.33080766 class 4: 0.08697148 class 5: 0.37604603 class 6: 0.0072344807 class 7: 0.2163677 class 8: 0.6778649 class 9: 0.010483054 class 10: 0.28229013 class 11: 0.08285885 class 12: 0.54856247 class 13: 0.5060702 class 14: 0.26826012 class 15: 0.79161125 class 16: 0.00043867234 class 17: 0.22526477 class 18: 0.13574767 class 19: 0.14906816 class 20: 0.2198876 Class Acc: class 0: 0.9055752 class 1: 0.1661803 class 2: 0.45422554 class 3: 0.33121628 class 4: 0.08705099 class 5: 0.38315275 class 6: 0.0072452705 class 7: 0.21683867 class 8: 0.6815347 class 9: 0.010607969 class 10: 0.301625 class 11: 0.083156176 class 12: 0.59717894 class 13: 0.5174191 class 14: 0.27290416 class 15: 0.86344343 class 16: 0.0004472701 class 17: 0.70130014 class 18: 0.41352695 class 19: 0.9158315 class 20: 0.64600176 `
> > > I used the command as following:
> > > `CUDA_VISIBLE_DEVICES=1 python -m torch.distributed.launch --nproc_per_node=1 run.py --batch_size 10 --dataset voc --name MIB_lr0-01_for_step0_lr0-001_for_step1 --task 15-5s --step 0 --lr 0.01 --epochs 30 --method MiB --opt_level O1 \ CUDA_VISIBLE_DEVICES=1 python -m torch.distributed.launch --nproc_per_node=1 run.py --batch_size 10 --dataset voc --name MIB_lr0-01_for_step0_lr0-001_for_step1 --task 15-5s --step 1 --lr 0.001 --epochs 30 --method MiB --opt_level O1 \ CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=2 run.py --batch_size 10 --dataset voc --name MIB_lr0-01_for_step0_lr0-001_for_step1 --task 15-5s --step 2 --lr 0.001 --epochs 30 --method MiB --opt_level O1 \ CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=2 run.py --batch_size 10 --dataset voc --name MIB_lr0-01_for_step0_lr0-001_for_step1 --task 15-5s --step 3 --lr 0.001 --epochs 30 --method MiB --opt_level O1 \ CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=2 run.py --batch_size 10 --dataset voc --name MIB_lr0-01_for_step0_lr0-001_for_step1 --task 15-5s --step 4 --lr 0.001 --epochs 30 --method MiB --opt_level O1 \ CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=2 run.py --batch_size 10 --dataset voc --name MIB_lr0-01_for_step0_lr0-001_for_step1 --task 15-5s --step 5 --lr 0.001 --epochs 30 --method MiB --opt_level O1 `
> > 
> > 
> > Hi @fcdl94 and @zhangchbin, just mention that I also noticed @zhangchbin was using the `--opt level O1` for training. As the `O1` are for mixed-precision training, should it also be the reason for the degradation of the mIoU?
> 
> Hi, @wuyujack , I have reproduced the performance of disjoint 15-5 using FP16, which do not reduce the performance. I think
> there are some other reasons, such as unstable training caused by few training samples. Do you have any ideas? Thanks.

Hi @zhangchbin , sorry for the late reply but I am not sure what's the true problem, as this situation does not occur from my side. And based on my reproduction results, the hypothesis of unstable training is not convincing to me for explaining your issue since all my results are quite consistent for the 1-15 classes after step 5 using different random seeds (42+ mIoU) and the final result of 1-20 is close the one reported in the paper, although for 1-15 it does not that high as the one reported in the paper (46.2 mIoU). As mentioned by @fcdl94 , I also recommend you to list the commands or even a screenshot of the configuration shown in the `TEXT` section in your `tf.events` in case that you did change any of the default settings, and also your environment information like PyTorch version and so on. BTW, did you change any part of the code that you have forgotten to mention?

**Comment by zhangchbin** [comment]
Hi, @wuyujack and @fcdl94 
Thanks for your help, and I will check the code or clone the repo. again.
I am sorry for the inconvenience caused by my trouble.
Thanks!

**Comment by zhangchbin** [comment]
Hi, @wuyujack and @fcdl94 
It seems that the number of training epochs is not long enough, resulting in unstable final results.

**Comment by fcdl94** [comment]
This is strange since I'm able to replicate my results without any effort. 
However, have you replicated the results?

**Comment by zhangchbin** [comment]
Hi, @fcdl94 
Do you use 
```--unce --unkd --loss_kd 100 --init_balanced```
in the 19-1 setting?

**Comment by fcdl94** [comment]
The loss_kd Is always 10 except in the15-5s scenario where it is 100. So for 19-1 is 10.

**Comment by zhangchbin** [comment]
But I find it is better than using 
```
--method MiB.
```

**Comment by fcdl94** [comment]
It is possible since we did not choose the best results on the test set, but we followed the validation protocol as explained in the paper. Other settings also may benefit from this test-performance tuning, but we believe this is not fair in comparison with previous methods.

**Comment by zhangchbin** [comment]
Hi,
If I use 
```
--overlap
```
, it means Disjoint or Overlapped?

**Comment by fcdl94** [comment]
it means overlapped

**Comment by zhangchbin** [comment]
Thanks for your help. We have solved this issue.
