### ISSUE TITLE
i want to use standard BN

### ISSUE THREAD

**Issue by JIA-HONG-CHU** [fcdl94/MiB#48]
Hello, i want to use batch normalization instead of In-place ABN. What setting should I revise ?. I only revised norm_act to std in argparser.py. But i got error torch.nn.modules.module.ModuleAttributeError: 'BatchNorm2d' object has no attribute 'activation'.
tks for help.

**Comment by fcdl94** [comment]
Hi @JIA-HONG-CHU.

To use standard batch norm I suggest you use "ABN", which is the "activated Batch Norm" version, which encapsulates standard batch norm followed by leaky-relu.
Please refer to the In-Place ABN library for the details.

**Comment by JIA-HONG-CHU** [comment]
ok, I modified the Pytorch BN2d to ABN and the code works fine. tks . I will close this issue. ;)
